[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  CI = "false"

# Enable React Router - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
